# Generated by Django 5.1.2 on 2024-11-20 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0009_propertyenquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_booking', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of booking')),
                ('date_starting', models.DateField(verbose_name='Date of start of tenancy')),
                ('date_ending', models.DateField(null=True, verbose_name='Date of end of tenancy')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Is payment made')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Property Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Booking')),
            ],
            options={
                'ordering': ('time_booking', 'date_starting', 'property'),
            },
        ),
    ]
