# Generated by Django 5.1.2 on 2024-10-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
