# Generated by Django 5.1.2 on 2024-10-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0, verbose_name='Number of bedrooms'),
        ),
    ]
