# Generated by Django 5.1.2 on 2024-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
        migrations.AddField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
        migrations.AddField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
        migrations.AddField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/property'),
        ),
    ]
