# Generated by Django 5.1.2 on 2024-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_picture_1_property_picture_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0, verbose_name='Number of Bathrooms'),
        ),
    ]
