# Generated by Django 5.1.2 on 2024-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
    ]
