# Generated by Django 5.1.2 on 2024-11-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_picture_1_alter_property_picture_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Type of Building',
                'verbose_name_plural': 'Types of Building',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Type of Sale',
                'verbose_name_plural': 'Types of Sale',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='building_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.buildingtype', verbose_name='Property Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.saletype', verbose_name='Type of Sale'),
        ),
    ]
